//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMdance.Revit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuiltInCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuiltInCategories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMdance.Revit.Resources.BuiltInCategories", typeof(BuiltInCategories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Devices.
        /// </summary>
        internal static string CommunicationDevices {
            get {
                return ResourceManager.GetString("CommunicationDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Devices.
        /// </summary>
        internal static string DataDevices {
            get {
                return ResourceManager.GetString("DataDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Equipment.
        /// </summary>
        internal static string ElectricalEquipment {
            get {
                return ResourceManager.GetString("ElectricalEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Fixtures.
        /// </summary>
        internal static string ElectricalFixtures {
            get {
                return ResourceManager.GetString("ElectricalFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Alarm Devices.
        /// </summary>
        internal static string FireAlarmDevices {
            get {
                return ResourceManager.GetString("FireAlarmDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Devices.
        /// </summary>
        internal static string LightingDevices {
            get {
                return ResourceManager.GetString("LightingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Fixtures.
        /// </summary>
        internal static string LightingFixtures {
            get {
                return ResourceManager.GetString("LightingFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Equipment.
        /// </summary>
        internal static string MechanicalEquipment {
            get {
                return ResourceManager.GetString("MechanicalEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse Call Devices.
        /// </summary>
        internal static string NurseCallDevices {
            get {
                return ResourceManager.GetString("NurseCallDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Devices.
        /// </summary>
        internal static string SecurityDevices {
            get {
                return ResourceManager.GetString("SecurityDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty Equipment.
        /// </summary>
        internal static string SpecialtyEquipment {
            get {
                return ResourceManager.GetString("SpecialtyEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Devices.
        /// </summary>
        internal static string TelephoneDevices {
            get {
                return ResourceManager.GetString("TelephoneDevices", resourceCulture);
            }
        }
    }
}
