//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMdance.Revit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Equipment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Equipment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMdance.Revit.Resources.Equipment", typeof(Equipment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air forced.
        /// </summary>
        internal static string CoolingMode_AF {
            get {
                return ResourceManager.GetString("CoolingMode_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        internal static string CoolingMode_AF_Short {
            get {
                return ResourceManager.GetString("CoolingMode_AF_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air forced water forced.
        /// </summary>
        internal static string CoolingMode_AFWF {
            get {
                return ResourceManager.GetString("CoolingMode_AFWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFWF.
        /// </summary>
        internal static string CoolingMode_AFWF_Short {
            get {
                return ResourceManager.GetString("CoolingMode_AFWF_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air natural.
        /// </summary>
        internal static string CoolingMode_AN {
            get {
                return ResourceManager.GetString("CoolingMode_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN.
        /// </summary>
        internal static string CoolingMode_AN_Short {
            get {
                return ResourceManager.GetString("CoolingMode_AN_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power.
        /// </summary>
        internal static string DisplayName_ActivePower {
            get {
                return ResourceManager.GetString("DisplayName_ActivePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power.
        /// </summary>
        internal static string DisplayName_ApparentPower {
            get {
                return ResourceManager.GetString("DisplayName_ApparentPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementary.
        /// </summary>
        internal static string DisplayName_Complementary {
            get {
                return ResourceManager.GetString("DisplayName_Complementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling mode.
        /// </summary>
        internal static string DisplayName_CoolingMode {
            get {
                return ResourceManager.GetString("DisplayName_CoolingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power factor.
        /// </summary>
        internal static string DisplayName_PowerFactor {
            get {
                return ResourceManager.GetString("DisplayName_PowerFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated primary current.
        /// </summary>
        internal static string DisplayName_PrimaryCurrent {
            get {
                return ResourceManager.GetString("DisplayName_PrimaryCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated primary voltage.
        /// </summary>
        internal static string DisplayName_PrimaryVoltage {
            get {
                return ResourceManager.GetString("DisplayName_PrimaryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection index.
        /// </summary>
        internal static string DisplayName_ProtectionIndex {
            get {
                return ResourceManager.GetString("DisplayName_ProtectionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated current.
        /// </summary>
        internal static string DisplayName_RatedCurrent {
            get {
                return ResourceManager.GetString("DisplayName_RatedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated power.
        /// </summary>
        internal static string DisplayName_RatedPower {
            get {
                return ResourceManager.GetString("DisplayName_RatedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated voltage.
        /// </summary>
        internal static string DisplayName_RatedVoltage {
            get {
                return ResourceManager.GetString("DisplayName_RatedVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated secondary current.
        /// </summary>
        internal static string DisplayName_SecondaryCurrent {
            get {
                return ResourceManager.GetString("DisplayName_SecondaryCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated secondary voltage.
        /// </summary>
        internal static string DisplayName_SecondaryVoltage {
            get {
                return ResourceManager.GetString("DisplayName_SecondaryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector group.
        /// </summary>
        internal static string DisplayName_VectorGroup {
            get {
                return ResourceManager.GetString("DisplayName_VectorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winding material.
        /// </summary>
        internal static string DisplayName_WindingMaterial {
            get {
                return ResourceManager.GetString("DisplayName_WindingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        internal static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended warranty.
        /// </summary>
        internal static string Property_ExtendedWarranty {
            get {
                return ResourceManager.GetString("Property_ExtendedWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory test reports.
        /// </summary>
        internal static string Property_FactoryTestReports {
            get {
                return ResourceManager.GetString("Property_FactoryTestReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation supervision.
        /// </summary>
        internal static string Property_InstallationSupervision {
            get {
                return ResourceManager.GetString("Property_InstallationSupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance contract.
        /// </summary>
        internal static string Property_MaintenanceContract {
            get {
                return ResourceManager.GetString("Property_MaintenanceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine packaging.
        /// </summary>
        internal static string Property_MarinePackaging {
            get {
                return ResourceManager.GetString("Property_MarinePackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate in Russian.
        /// </summary>
        internal static string Property_NameplateInRussian {
            get {
                return ResourceManager.GetString("Property_NameplateInRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport GOST.
        /// </summary>
        internal static string Property_PassportGOST {
            get {
                return ResourceManager.GetString("Property_PassportGOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced noise level.
        /// </summary>
        internal static string Property_ReducedNoiseLevel {
            get {
                return ResourceManager.GetString("Property_ReducedNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply of spare parts.
        /// </summary>
        internal static string Property_SupplyOfSpareParts {
            get {
                return ResourceManager.GetString("Property_SupplyOfSpareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration damping stands.
        /// </summary>
        internal static string Property_VibrationDampingStands {
            get {
                return ResourceManager.GetString("Property_VibrationDampingStands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer.
        /// </summary>
        internal static string Transformer {
            get {
                return ResourceManager.GetString("Transformer", resourceCulture);
            }
        }
    }
}
