//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMdance.Revit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMdance.Revit.Resources.TransactionNames", typeof(TransactionNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filters.
        /// </summary>
        internal static string AddFilters {
            get {
                return ResourceManager.GetString("AddFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Routes.
        /// </summary>
        internal static string CableRouting {
            get {
                return ResourceManager.GetString("CableRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Cable Routing.
        /// </summary>
        internal static string DrawCableRouting {
            get {
                return ResourceManager.GetString("DrawCableRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Patterns.
        /// </summary>
        internal static string LinePatterns {
            get {
                return ResourceManager.GetString("LinePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Styles.
        /// </summary>
        internal static string LineStyles {
            get {
                return ResourceManager.GetString("LineStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify element attributes.
        /// </summary>
        internal static string ModifyElementAttributes {
            get {
                return ResourceManager.GetString("ModifyElementAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameters.
        /// </summary>
        internal static string Parameters_Add {
            get {
                return ResourceManager.GetString("Parameters_Add", resourceCulture);
            }
        }
    }
}
