namespace BIMdance.Revit.Utils.Revit.Parameters;

public static class ParameterTypeConverter
{
    public static ParameterTypeProxy GetParameterType(int id)
    {
        return (ParameterTypeProxy)id;
    }

    public static ParameterTypeProxy GetParameterType(string name)
    {
        return ParameterTypeIndexes.TryGetValue(name, out var id)
            ? (ParameterTypeProxy)id
            : ParameterTypeProxy.Invalid;
    }

    public static string GetParameterTypeName(ParameterTypeProxy parameterType)
    {
        return ParameterTypeNames.TryGetValue((int)parameterType, out var name)
            ? name
            : throw new ArgumentOutOfRangeException($"{nameof(parameterType)}", $"[{(int)parameterType}] {parameterType}", new ArgumentOutOfRangeException().Message);
    }

    private static readonly SortedDictionary<string, int> ParameterTypeIndexes = new()
    {
        ["ACCELERATION"] = 192,
        ["ANGLE"] = 7,
        ["AREA"] = 5,
        ["AREA_FORCE"] = 13,
        ["AREA_SPRING_COEFFICIENT"] = 154,
        ["BAR_DIAMETER"] = 193,
        ["CRACK_WIDTH"] = 194,
        ["CURRENCY"] = 172,
        ["DISPLACEMENT/DEFLECTION"] = 195,
        ["ELECTRICAL_APPARENT_POWER"] = 134,
        ["CABLETRAY_SIZE"] = 182,
        ["CONDUIT_SIZE"] = 183,
        ["ELECTRICAL_CURRENT"] = 119,
        ["ELECTRICAL_DEMAND_FACTOR"] = 186,
        ["ELECTRICAL_EFFICACY"] = 173,
        ["ELECTRICAL_FREQUENCY"] = 121,
        ["ELECTRICAL_ILLUMINANCE"] = 122,
        ["ELECTRICAL_LUMINANCE"] = 178,
        ["ELECTRICAL_LUMINOUS_FLUX"] = 123,
        ["ELECTRICAL_LUMINOUS_INTENSITY"] = 177,
        ["ELECTRICAL_POTENTIAL"] = 120,
        ["ELECTRICAL_POWER"] = 124,
        ["ELECTRICAL_POWER_DENSITY"] = 135,
        ["ELECTRICAL_RESISTIVITY"] = 221,
        ["ELECTRICAL_TEMPERATURE"] = 181,
        ["ELECTRICAL_WATTAGE"] = 174,
        ["ENERGY"] = 196,
        ["FAMILYTYPE"] = 17,
        ["FIXTUREUNIT"] = 16,
        ["FORCE"] = 11,
        ["HVAC_AIR_FLOW"] = 115,
        ["HVAC_AIRFLOW_DENSITY"] = 158,
        ["HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD"] = 167,
        ["HVAC_AIRFLOW_DIVIDED_BY_VOLUME"] = 166,
        ["HVAC_AREA_DIVIDED_BY_COOLING_LOAD"] = 168,
        ["HVAC_AREA_DIVIDED_BY_HEATING_LOAD"] = 179,
        ["HVAC_COEFFICIENT_OF_HEAT_TRANSFER"] = 157,
        ["HVAC_COOLING_LOAD_DIVIDED_BY_AREA"] = 161,
        ["HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME"] = 162,
        ["HVAC_COOLING_LOAD"] = 160,
        ["HVAC_CROSS_SECTION"] = 117,
        ["HVAC_DENSITY"] = 107,
        ["HVAC_DUCT_INSULATION_THICKNESS"] = 187,
        ["HVAC_DUCT_LINING_THICKNESS"] = 188,
        ["HVAC_DUCT_SIZE"] = 116,
        ["HVAC_ENERGY"] = 108,
        ["HVAC_FACTOR"] = 180,
        ["HVAC_FRICTION"] = 109,
        ["HVAC_HEAT_GAIN"] = 118,
        ["HVAC_HEATING_LOAD_DIVIDED_BYAREA"] = 164,
        ["HVAC_HEATING_LOAD_DIVIDED_BYVOLUME"] = 165,
        ["HVAC_HEATING_LOAD"] = 163,
        ["HVAC_PERMEABILITY"] = 220,
        ["HVAC_POWER"] = 110,
        ["HVAC_POWER_DENSITY"] = 111,
        ["HVAC_PRESSURE"] = 112,
        ["HVAC_ROUGHNESS"] = 125,
        ["HVAC_SLOPE"] = 170,
        ["HVAC_SPECIFIC_HEAT"] = 218,
        ["HVAC_SPECIFIC_HEAT_OF_VAPORIZATION"] = 219,
        ["HVAC_TEMPERATURE"] = 113,
        ["HVAC_THERMAL_CONDUCTIVITY"] = 217,
        ["HVAC_THERMAL_MASS"] = 191,
        ["HVAC_THERMAL_RESISTANCE"] = 190,
        ["HVAC_VELOCITY"] = 114,
        ["HVAC_VISCOSITY"] = 156,
        ["IMAGE"] = 19,
        ["INTEGER"] = 2,
        ["INVALID"] = 0,
        ["LENGTH"] = 4,
        ["LINEAR_FORCE"] = 12,
        ["LINEAR_MOMENT"] = 148,
        ["LOADCLASSIFICATION"] = 18,
        ["MASS"] = 198,
        ["MASS_DENSITY"] = 222,
        ["MASS_PER_UNIT_AREA"] = 223,
        ["MASS_PER_UNIT_LENGTH"] = 199,
        ["MATERIAL"] = 9,
        ["MOMENT"] = 14,
        ["MOMENT_OF_INERTIA"] = 200,
        ["NUMBER"] = 3,
        ["NOOFPOLES"] = 15,
        ["PERIOD"] = 202,
        ["PIPE_DIMENSION"] = 224,
        ["PIPE_INSULATION_THICKNESS"] = 189,
        ["PIPE_MASS"] = 225,
        ["PIPE_MASS_PER_UNIT_LENGTH"] = 226,
        ["PIPE_SIZE"] = 143,
        ["PIPING_DENSITY"] = 136,
        ["PIPING_FLOW"] = 137,
        ["PIPING_FRICTION"] = 138,
        ["PIPING_PRESSURE"] = 139,
        ["PIPING_ROUGHNESS"] = 144,
        ["PIPING_SLOPE"] = 171,
        ["PIPING_TEMPERATURE"] = 140,
        ["PIPING_VELOCITY"] = 141,
        ["PIPING_VISCOSITY"] = 142,
        ["PIPING_VOLUME"] = 155,
        ["PULSATION"] = 203,
        ["REINFORCEMENT_AREA"] = 204,
        ["REINFORCEMENT_AREA_PER_UNIT_LENGTH"] = 205,
        ["REINFORCEMENT_COVER"] = 206,
        ["REINFORCEMENT_LENGTH"] = 185,
        ["REINFORCEMENT_SPACING"] = 207,
        ["REINFORCEMENT_VOLUME"] = 184,
        ["ROTATION"] = 208,
        ["SECTION_AREA"] = 209,
        ["SECTION_DIMENSION"] = 210,
        ["SECTION_MODULUS"] = 211,
        ["SECTION_PROPERTY"] = 212,
        ["SLOPE"] = 159,
        ["STRESS"] = 145,
        ["STRUCTURAL_FREQUENCY"] = 197,
        ["VELOCITY"] = 213,
        ["SURFACE_AREA"] = 201,
        ["TEXT"] = 1,
        ["THERMAL_EXPANSION_COEFFICIENT"] = 147,
        ["UNIT_WEIGHT"] = 146,
        ["URL"] = 8,
        ["VOLUME"] = 6,
        ["WARPING_CONSTANT"] = 214,
        ["WEIGHT"] = 215,
        ["WEIGHT_PER_UNIT_LENGTH"] = 216,
        ["WIRE_SIZE"] = 169,
        ["YESNO"] = 10,
    };

    private static readonly SortedDictionary<int, string> ParameterTypeNames = new()
    {
        [0] = "INVALID",
        [1] = "TEXT",
        [2] = "INTEGER",
        [3] = "NUMBER",
        [4] = "LENGTH",
        [5] = "AREA",
        [6] = "VOLUME",
        [7] = "ANGLE",
        [8] = "URL",
        [9] = "MATERIAL",
        [10] = "YESNO",
        [11] = "FORCE",
        [12] = "LINEAR_FORCE",
        [13] = "AREA_FORCE",
        [14] = "MOMENT",
        [15] = "NOOFPOLES",
        [16] = "FIXTUREUNIT",
        [17] = "FAMILYTYPE",
        [18] = "LOADCLASSIFICATION",
        [19] = "IMAGE",
        [107] = "HVAC_DENSITY",
        [108] = "HVAC_ENERGY",
        [109] = "HVAC_FRICTION",
        [110] = "HVAC_POWER",
        [111] = "HVAC_POWER_DENSITY",
        [112] = "HVAC_PRESSURE",
        [113] = "HVAC_TEMPERATURE",
        [114] = "HVAC_VELOCITY",
        [115] = "HVAC_AIR_FLOW",
        [116] = "HVAC_DUCT_SIZE",
        [117] = "HVAC_CROSS_SECTION",
        [118] = "HVAC_HEAT_GAIN",
        [119] = "ELECTRICAL_CURRENT",
        [120] = "ELECTRICAL_POTENTIAL",
        [121] = "ELECTRICAL_FREQUENCY",
        [122] = "ELECTRICAL_ILLUMINANCE",
        [123] = "ELECTRICAL_LUMINOUS_FLUX",
        [124] = "ELECTRICAL_POWER",
        [125] = "HVAC_ROUGHNESS",
        [134] = "ELECTRICAL_APPARENT_POWER",
        [135] = "ELECTRICAL_POWER_DENSITY",
        [136] = "PIPING_DENSITY",
        [137] = "PIPING_FLOW",
        [138] = "PIPING_FRICTION",
        [139] = "PIPING_PRESSURE",
        [140] = "PIPING_TEMPERATURE",
        [141] = "PIPING_VELOCITY",
        [142] = "PIPING_VISCOSITY",
        [143] = "PIPE_SIZE",
        [144] = "PIPING_ROUGHNESS",
        [145] = "STRESS",
        [146] = "UNIT_WEIGHT",
        [147] = "THERMAL_EXPANSION_COEFFICIENT",
        [148] = "LINEAR_MOMENT",
        [154] = "AREA_SPRING_COEFFICIENT",
        [155] = "PIPING_VOLUME",
        [156] = "HVAC_VISCOSITY",
        [157] = "HVAC_COEFFICIENT_OF_HEAT_TRANSFER",
        [158] = "HVAC_AIRFLOW_DENSITY",
        [159] = "SLOPE",
        [160] = "HVAC_COOLING_LOAD",
        [161] = "HVAC_COOLING_LOAD_DIVIDED_BY_AREA",
        [162] = "HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME",
        [163] = "HVAC_HEATING_LOAD",
        [164] = "HVAC_HEATING_LOAD_DIVIDED_BYAREA",
        [165] = "HVAC_HEATING_LOAD_DIVIDED_BYVOLUME",
        [166] = "HVAC_AIRFLOW_DIVIDED_BY_VOLUME",
        [167] = "HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD",
        [168] = "HVAC_AREA_DIVIDED_BY_COOLING_LOAD",
        [169] = "WIRE_SIZE",
        [170] = "HVAC_SLOPE",
        [171] = "PIPING_SLOPE",
        [172] = "CURRENCY",
        [173] = "ELECTRICAL_EFFICACY",
        [174] = "ELECTRICAL_WATTAGE",
        [177] = "ELECTRICAL_LUMINOUS_INTENSITY",
        [178] = "ELECTRICAL_LUMINANCE",
        [179] = "HVAC_AREA_DIVIDED_BY_HEATING_LOAD",
        [180] = "HVAC_FACTOR",
        [181] = "ELECTRICAL_TEMPERATURE",
        [182] = "CABLETRAY_SIZE",
        [183] = "CONDUIT_SIZE",
        [184] = "REINFORCEMENT_VOLUME",
        [185] = "REINFORCEMENT_LENGTH",
        [186] = "ELECTRICAL_DEMAND_FACTOR",
        [187] = "HVAC_DUCT_INSULATION_THICKNESS",
        [188] = "HVAC_DUCT_LINING_THICKNESS",
        [189] = "PIPE_INSULATION_THICKNESS",
        [190] = "HVAC_THERMAL_RESISTANCE",
        [191] = "HVAC_THERMAL_MASS",
        [192] = "ACCELERATION",
        [193] = "BAR_DIAMETER",
        [194] = "CRACK_WIDTH",
        [195] = "DISPLACEMENT/DEFLECTION",
        [196] = "ENERGY",
        [197] = "STRUCTURAL_FREQUENCY",
        [198] = "MASS",
        [199] = "MASS_PER_UNIT_LENGTH",
        [200] = "MOMENT_OF_INERTIA",
        [201] = "SURFACE_AREA",
        [202] = "PERIOD",
        [203] = "PULSATION",
        [204] = "REINFORCEMENT_AREA",
        [205] = "REINFORCEMENT_AREA_PER_UNIT_LENGTH",
        [206] = "REINFORCEMENT_COVER",
        [207] = "REINFORCEMENT_SPACING",
        [208] = "ROTATION",
        [209] = "SECTION_AREA",
        [210] = "SECTION_DIMENSION",
        [211] = "SECTION_MODULUS",
        [212] = "SECTION_PROPERTY",
        [213] = "VELOCITY",
        [214] = "WARPING_CONSTANT",
        [215] = "WEIGHT",
        [216] = "WEIGHT_PER_UNIT_LENGTH",
        [217] = "HVAC_THERMAL_CONDUCTIVITY",
        [218] = "HVAC_SPECIFIC_HEAT",
        [219] = "HVAC_SPECIFIC_HEAT_OF_VAPORIZATION",
        [220] = "HVAC_PERMEABILITY",
        [221] = "ELECTRICAL_RESISTIVITY",
        [222] = "MASS_DENSITY",
        [223] = "MASS_PER_UNIT_AREA",
        [224] = "PIPE_DIMENSION",
        [225] = "PIPE_MASS",
        [226] = "PIPE_MASS_PER_UNIT_LENGTH",
    };
}